fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "cyril.champrou@lapiscine.pro"
    sender_name: "cyril.champrou@lapiscine.pro"